# Secret Structure Documentation

**Purpose**: Document required Kubernetes secrets and their structure

**Version**: 1.0.0

## Overview

This document defines the structure and requirements for Kubernetes secrets used by the Todo AI Chatbot application. Secrets must be created manually before deploying the Helm chart.

## Required Secrets

### 1. Application Secrets

**Secret Name**: `app-secrets`

**Namespace**: `todo-app`

**Type**: `Opaque`

**Required Keys**:

| Key | Description | Format | Example | Source |
|-----|-------------|--------|---------|--------|
| `COHERE_API_KEY` | Cohere API authentication key | String | `co_xxxxxxxxxxxxx` | Cohere dashboard |
| `DATABASE_URL` | Neon PostgreSQL connection string | PostgreSQL URL | `postgresql://user:pass@host/db?sslmode=require` | Neon dashboard |
| `JWT_SECRET` | JWT signing secret for Better Auth | String (32+ chars) | `your-secure-random-string-here` | Generated |

## Creation Methods

### Method 1: kubectl create secret (Recommended)

```bash
# Create secret from literal values
kubectl create secret generic app-secrets \
  --from-literal=COHERE_API_KEY='your-cohere-api-key' \
  --from-literal=DATABASE_URL='postgresql://user:pass@host/db?sslmode=require' \
  --from-literal=JWT_SECRET='your-jwt-secret' \
  --namespace=todo-app
```

### Method 2: kubectl apply with YAML

**⚠️ WARNING**: Never commit this file to version control!

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: todo-app
type: Opaque
stringData:
  COHERE_API_KEY: "your-cohere-api-key"
  DATABASE_URL: "postgresql://user:pass@host/db?sslmode=require"
  JWT_SECRET: "your-jwt-secret"
```

Apply:
```bash
kubectl apply -f secret.yaml
```

### Method 3: From .env file

Create `.env` file (add to .gitignore):
```
COHERE_API_KEY=your-cohere-api-key
DATABASE_URL=postgresql://user:pass@host/db?sslmode=require
JWT_SECRET=your-jwt-secret
```

Create secret:
```bash
kubectl create secret generic app-secrets \
  --from-env-file=.env \
  --namespace=todo-app
```

## Secret Consumption

### Environment Variables in Pods

Secrets are injected as environment variables in pod containers:

```yaml
# Backend Deployment
env:
  - name: COHERE_API_KEY
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: COHERE_API_KEY
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: DATABASE_URL
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: JWT_SECRET
```

### Application Access

**Backend (Python/FastAPI)**:
```python
import os

COHERE_API_KEY = os.getenv("COHERE_API_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
JWT_SECRET = os.getenv("JWT_SECRET")
```

**Frontend (Next.js)**:
```javascript
// Backend URL is passed via environment variable
const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://backend-service:8000';
```

## Validation

### Verify Secret Creation

```bash
# Check if secret exists
kubectl get secret app-secrets -n todo-app

# View secret keys (values are base64-encoded)
kubectl get secret app-secrets -n todo-app -o yaml

# Decode a specific key (for verification only - don't log in production)
kubectl get secret app-secrets -n todo-app -o jsonpath='{.data.COHERE_API_KEY}' | base64 -d
```

### Verify Secret Injection

```bash
# Check environment variables in running pod
kubectl exec -it <backend-pod-name> -n todo-app -- env | grep -E 'COHERE|DATABASE|JWT'

# Should NOT show actual values in describe (shows secret reference only)
kubectl describe pod <backend-pod-name> -n todo-app | grep -A 5 "Environment"
```

## Security Best Practices

### ✅ DO

- Create secrets before deploying application
- Use strong, randomly generated values for JWT_SECRET
- Rotate secrets regularly (at least quarterly)
- Use different secrets for dev/staging/prod environments
- Add secret files to .gitignore
- Use kubectl create secret (values not stored in files)
- Restrict access to secrets using RBAC
- Use namespace isolation

### ❌ DON'T

- Commit secrets to version control
- Store secrets in Helm values.yaml
- Log secret values
- Share secrets via insecure channels (email, Slack)
- Use weak or predictable secrets
- Reuse secrets across environments
- Include secrets in container images
- Expose secrets in pod describe output

## Secret Rotation

### Rotation Process

1. **Create new secret with updated values**:
   ```bash
   kubectl create secret generic app-secrets \
     --from-literal=COHERE_API_KEY='new-key' \
     --from-literal=DATABASE_URL='new-url' \
     --from-literal=JWT_SECRET='new-secret' \
     --namespace=todo-app \
     --dry-run=client -o yaml | kubectl apply -f -
   ```

2. **Restart pods to pick up new values**:
   ```bash
   kubectl rollout restart deployment/backend-deployment -n todo-app
   kubectl rollout restart deployment/frontend-deployment -n todo-app
   ```

3. **Verify new secrets are loaded**:
   ```bash
   kubectl logs -l app=backend -n todo-app --tail=20
   ```

### Rotation Schedule

- **JWT_SECRET**: Every 90 days
- **COHERE_API_KEY**: When compromised or annually
- **DATABASE_URL**: When password changes (per Neon policy)

## Troubleshooting

### Secret Not Found

**Error**: `Error: secrets "app-secrets" not found`

**Solution**:
```bash
# Verify namespace
kubectl get secrets -n todo-app

# Create secret if missing
kubectl create secret generic app-secrets \
  --from-literal=COHERE_API_KEY='...' \
  --from-literal=DATABASE_URL='...' \
  --from-literal=JWT_SECRET='...' \
  --namespace=todo-app
```

### Invalid Secret Key

**Error**: `Error: couldn't find key COHERE_API_KEY in Secret todo-app/app-secrets`

**Solution**:
```bash
# Check existing keys
kubectl get secret app-secrets -n todo-app -o jsonpath='{.data}' | jq 'keys'

# Update secret with correct keys
kubectl delete secret app-secrets -n todo-app
kubectl create secret generic app-secrets \
  --from-literal=COHERE_API_KEY='...' \
  --from-literal=DATABASE_URL='...' \
  --from-literal=JWT_SECRET='...' \
  --namespace=todo-app
```

### Secret Not Injected

**Error**: Environment variable is empty in pod

**Solution**:
```bash
# Verify secret reference in deployment
kubectl get deployment backend-deployment -n todo-app -o yaml | grep -A 10 "env:"

# Restart deployment
kubectl rollout restart deployment/backend-deployment -n todo-app
```

## Example: Complete Secret Setup

```bash
# 1. Create namespace
kubectl create namespace todo-app

# 2. Generate JWT secret
JWT_SECRET=$(openssl rand -base64 32)

# 3. Get Cohere API key from dashboard
COHERE_API_KEY="your-cohere-api-key"

# 4. Get Neon database URL from dashboard
DATABASE_URL="postgresql://user:pass@host/db?sslmode=require"

# 5. Create secret
kubectl create secret generic app-secrets \
  --from-literal=COHERE_API_KEY="$COHERE_API_KEY" \
  --from-literal=DATABASE_URL="$DATABASE_URL" \
  --from-literal=JWT_SECRET="$JWT_SECRET" \
  --namespace=todo-app

# 6. Verify
kubectl get secret app-secrets -n todo-app

# 7. Deploy application
helm install todo-app helm/todo-app -n todo-app
```

## References

- [Kubernetes Secrets Documentation](https://kubernetes.io/docs/concepts/configuration/secret/)
- [Kubernetes Secret Best Practices](https://kubernetes.io/docs/concepts/security/secrets-good-practices/)
- [Cohere API Keys](https://dashboard.cohere.ai/api-keys)
- [Neon Connection Strings](https://neon.tech/docs/connect/connect-from-any-app)
